g++ -std=c++11\
	SyntaxAnalyzer/Temp.cpp\
 	LexicalAnalyzer/TableEntry.cpp\
	LexicalAnalyzer/Token.cpp\
	LexicalAnalyzer/Buffer.cpp\
	LexicalAnalyzer/SymbolTable.cpp\
	LexicalAnalyzer/LexicalAnalyzer.cpp\
	SyntaxAnalyzer/Declaration.cpp\
	SyntaxAnalyzer/Command.cpp\
	SyntaxAnalyzer/Expr.cpp\
	SyntaxAnalyzer/If.cpp\
	SyntaxAnalyzer/While.cpp\
	SyntaxAnalyzer/Print.cpp\
	SyntaxAnalyzer/And.cpp\
	SyntaxAnalyzer/Or.cpp\
	SyntaxAnalyzer/Eq.cpp\
	SyntaxAnalyzer/Ne.cpp\
	SyntaxAnalyzer/Gt.cpp\
	SyntaxAnalyzer/Gte.cpp\
	SyntaxAnalyzer/Lt.cpp\
	SyntaxAnalyzer/Lte.cpp\
	SyntaxAnalyzer/Plus.cpp\
	SyntaxAnalyzer/Minus.cpp\
	SyntaxAnalyzer/Mult.cpp\
	SyntaxAnalyzer/Div.cpp\
	SyntaxAnalyzer/Id.cpp\
	SyntaxAnalyzer/Attr.cpp\
	SyntaxAnalyzer/Read.cpp\
	SyntaxAnalyzer/Num.cpp\
	SyntaxAnalyzer/AbstractSyntaxTree.cpp\
	SyntaxAnalyzer/SyntaxAnalyzer.cpp\
	Main.cpp -o Main
